/**
 * generated by Xtext 2.12.0
 */
package com.hypermodel.games.engine;

import com.hypermodel.games.engine.AbstractGameDSLRuntimeModule;
import com.hypermodel.games.engine.converter.GameQualifiedNameProvider;
import com.hypermodel.games.engine.converter.GameValueConverter;
import com.hypermodel.games.engine.generator.GameDSLGenerator;
import com.hypermodel.games.engine.jvmmodel.GameDSLJvmModelInferrer;
import com.hypermodel.games.engine.scoping.GameDSLScopeProvider;
import com.hypermodel.games.engine.validation.GameDSLValidator;
import org.eclipse.xtext.conversion.IValueConverterService;
import org.eclipse.xtext.generator.IGenerator;
import org.eclipse.xtext.naming.IQualifiedNameProvider;
import org.eclipse.xtext.resource.persistence.IResourceStorageFacade;
import org.eclipse.xtext.scoping.IScopeProvider;
import org.eclipse.xtext.xbase.jvmmodel.IJvmModelInferrer;
import org.eclipse.xtext.xbase.resource.BatchLinkableResourceStorageFacade;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class GameDSLRuntimeModule extends AbstractGameDSLRuntimeModule {
  @Override
  public Class<? extends IScopeProvider> bindIScopeProvider() {
    return GameDSLScopeProvider.class;
  }
  
  @Override
  public Class<? extends GameDSLValidator> bindGameDSLValidator() {
    return GameDSLValidator.class;
  }
  
  @Override
  public Class<? extends IGenerator> bindIGenerator() {
    return GameDSLGenerator.class;
  }
  
  @Override
  public Class<? extends IJvmModelInferrer> bindIJvmModelInferrer() {
    return GameDSLJvmModelInferrer.class;
  }
  
  @Override
  public Class<? extends IQualifiedNameProvider> bindIQualifiedNameProvider() {
    return GameQualifiedNameProvider.class;
  }
  
  @Override
  public Class<? extends IValueConverterService> bindIValueConverterService() {
    return GameValueConverter.class;
  }
  
  public Class<? extends IResourceStorageFacade> bindResourceStorageFacade() {
    return BatchLinkableResourceStorageFacade.class;
  }
}
