/**
 * generated by Xtext 2.12.0
 */
package com.hypermodel.games.engine;

import com.google.inject.Binder;
import com.hypermodel.games.engine.AbstractGameDSLRuntimeModule;
import com.hypermodel.games.engine.generator.GameDSLGenerator;
import com.hypermodel.games.engine.generator.GameOutputConfigurationProvider;
import com.hypermodel.games.engine.jvmmodel.GameDSLJvmModelInferrer;
import com.hypermodel.games.engine.scoping.GameDSLScopeProvider;
import com.hypermodel.games.engine.validation.GameDSLValidator;
import javax.inject.Singleton;
import org.eclipse.xtext.generator.IGenerator;
import org.eclipse.xtext.generator.IOutputConfigurationProvider;
import org.eclipse.xtext.scoping.IScopeProvider;
import org.eclipse.xtext.xbase.jvmmodel.IJvmModelInferrer;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class GameDSLRuntimeModule extends AbstractGameDSLRuntimeModule {
  @Override
  public void configure(final Binder binder) {
    super.configure(binder);
    binder.<IOutputConfigurationProvider>bind(IOutputConfigurationProvider.class).to(GameOutputConfigurationProvider.class).in(Singleton.class);
  }
  
  @Override
  public Class<? extends IScopeProvider> bindIScopeProvider() {
    return GameDSLScopeProvider.class;
  }
  
  @Override
  public Class<? extends GameDSLValidator> bindGameDSLValidator() {
    return GameDSLValidator.class;
  }
  
  @Override
  public Class<? extends IGenerator> bindIGenerator() {
    return GameDSLGenerator.class;
  }
  
  @Override
  public Class<? extends IJvmModelInferrer> bindIJvmModelInferrer() {
    return GameDSLJvmModelInferrer.class;
  }
}
