/**
 * generated by Xtext 2.13.0
 */
package com.hypermodel.games.engine.gameDSL;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Game Platform</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see com.hypermodel.games.engine.gameDSL.GameDSLPackage#getGamePlatform()
 * @model
 * @generated
 */
public enum GamePlatform implements Enumerator
{
  /**
   * The '<em><b>Android</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ANDROID_VALUE
   * @generated
   * @ordered
   */
  ANDROID(0, "android", "android"),

  /**
   * The '<em><b>Desktop</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DESKTOP_VALUE
   * @generated
   * @ordered
   */
  DESKTOP(1, "desktop", "desktop"),

  /**
   * The '<em><b>Html</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #HTML_VALUE
   * @generated
   * @ordered
   */
  HTML(2, "html", "html"),

  /**
   * The '<em><b>Ios</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #IOS_VALUE
   * @generated
   * @ordered
   */
  IOS(3, "ios", "ios"),

  /**
   * The '<em><b>Iosmoe</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #IOSMOE_VALUE
   * @generated
   * @ordered
   */
  IOSMOE(4, "iosmoe", "ios-moe");

  /**
   * The '<em><b>Android</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Android</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ANDROID
   * @model name="android"
   * @generated
   * @ordered
   */
  public static final int ANDROID_VALUE = 0;

  /**
   * The '<em><b>Desktop</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Desktop</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #DESKTOP
   * @model name="desktop"
   * @generated
   * @ordered
   */
  public static final int DESKTOP_VALUE = 1;

  /**
   * The '<em><b>Html</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Html</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #HTML
   * @model name="html"
   * @generated
   * @ordered
   */
  public static final int HTML_VALUE = 2;

  /**
   * The '<em><b>Ios</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Ios</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #IOS
   * @model name="ios"
   * @generated
   * @ordered
   */
  public static final int IOS_VALUE = 3;

  /**
   * The '<em><b>Iosmoe</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Iosmoe</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #IOSMOE
   * @model name="iosmoe" literal="ios-moe"
   * @generated
   * @ordered
   */
  public static final int IOSMOE_VALUE = 4;

  /**
   * An array of all the '<em><b>Game Platform</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final GamePlatform[] VALUES_ARRAY =
    new GamePlatform[]
    {
      ANDROID,
      DESKTOP,
      HTML,
      IOS,
      IOSMOE,
    };

  /**
   * A public read-only list of all the '<em><b>Game Platform</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<GamePlatform> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Game Platform</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static GamePlatform get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      GamePlatform result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Game Platform</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static GamePlatform getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      GamePlatform result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Game Platform</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static GamePlatform get(int value)
  {
    switch (value)
    {
      case ANDROID_VALUE: return ANDROID;
      case DESKTOP_VALUE: return DESKTOP;
      case HTML_VALUE: return HTML;
      case IOS_VALUE: return IOS;
      case IOSMOE_VALUE: return IOSMOE;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private GamePlatform(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //GamePlatform
