/**
 * generated by hypermodels.com with Xtext 2.13.0
 */
package com.hypermodel.games.engine.gameDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Game Tile</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.hypermodel.games.engine.gameDSL.GameTile#getName <em>Name</em>}</li>
 *   <li>{@link com.hypermodel.games.engine.gameDSL.GameTile#getId <em>Id</em>}</li>
 *   <li>{@link com.hypermodel.games.engine.gameDSL.GameTile#isHasObjectLayer <em>Has Object Layer</em>}</li>
 *   <li>{@link com.hypermodel.games.engine.gameDSL.GameTile#getObjectLayer <em>Object Layer</em>}</li>
 *   <li>{@link com.hypermodel.games.engine.gameDSL.GameTile#isHasTileLayer <em>Has Tile Layer</em>}</li>
 *   <li>{@link com.hypermodel.games.engine.gameDSL.GameTile#getTileLayer <em>Tile Layer</em>}</li>
 * </ul>
 *
 * @see com.hypermodel.games.engine.gameDSL.GameDSLPackage#getGameTile()
 * @model
 * @generated
 */
public interface GameTile extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.hypermodel.games.engine.gameDSL.GameDSLPackage#getGameTile_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.hypermodel.games.engine.gameDSL.GameTile#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Id</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' attribute.
   * @see #setId(int)
   * @see com.hypermodel.games.engine.gameDSL.GameDSLPackage#getGameTile_Id()
   * @model
   * @generated
   */
  int getId();

  /**
   * Sets the value of the '{@link com.hypermodel.games.engine.gameDSL.GameTile#getId <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' attribute.
   * @see #getId()
   * @generated
   */
  void setId(int value);

  /**
   * Returns the value of the '<em><b>Has Object Layer</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Has Object Layer</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Has Object Layer</em>' attribute.
   * @see #setHasObjectLayer(boolean)
   * @see com.hypermodel.games.engine.gameDSL.GameDSLPackage#getGameTile_HasObjectLayer()
   * @model
   * @generated
   */
  boolean isHasObjectLayer();

  /**
   * Sets the value of the '{@link com.hypermodel.games.engine.gameDSL.GameTile#isHasObjectLayer <em>Has Object Layer</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Has Object Layer</em>' attribute.
   * @see #isHasObjectLayer()
   * @generated
   */
  void setHasObjectLayer(boolean value);

  /**
   * Returns the value of the '<em><b>Object Layer</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Object Layer</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Object Layer</em>' reference.
   * @see #setObjectLayer(GameLayer)
   * @see com.hypermodel.games.engine.gameDSL.GameDSLPackage#getGameTile_ObjectLayer()
   * @model
   * @generated
   */
  GameLayer getObjectLayer();

  /**
   * Sets the value of the '{@link com.hypermodel.games.engine.gameDSL.GameTile#getObjectLayer <em>Object Layer</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Object Layer</em>' reference.
   * @see #getObjectLayer()
   * @generated
   */
  void setObjectLayer(GameLayer value);

  /**
   * Returns the value of the '<em><b>Has Tile Layer</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Has Tile Layer</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Has Tile Layer</em>' attribute.
   * @see #setHasTileLayer(boolean)
   * @see com.hypermodel.games.engine.gameDSL.GameDSLPackage#getGameTile_HasTileLayer()
   * @model
   * @generated
   */
  boolean isHasTileLayer();

  /**
   * Sets the value of the '{@link com.hypermodel.games.engine.gameDSL.GameTile#isHasTileLayer <em>Has Tile Layer</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Has Tile Layer</em>' attribute.
   * @see #isHasTileLayer()
   * @generated
   */
  void setHasTileLayer(boolean value);

  /**
   * Returns the value of the '<em><b>Tile Layer</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Tile Layer</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tile Layer</em>' reference.
   * @see #setTileLayer(GameLayer)
   * @see com.hypermodel.games.engine.gameDSL.GameDSLPackage#getGameTile_TileLayer()
   * @model
   * @generated
   */
  GameLayer getTileLayer();

  /**
   * Sets the value of the '{@link com.hypermodel.games.engine.gameDSL.GameTile#getTileLayer <em>Tile Layer</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tile Layer</em>' reference.
   * @see #getTileLayer()
   * @generated
   */
  void setTileLayer(GameLayer value);

} // GameTile
