/**
 * generated by hypermodels.com with Xtext 2.13.0
 */
package com.hypermodel.games.engine.gameDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Game Platform Config</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.hypermodel.games.engine.gameDSL.GamePlatformConfig#getAndroid <em>Android</em>}</li>
 *   <li>{@link com.hypermodel.games.engine.gameDSL.GamePlatformConfig#getIos <em>Ios</em>}</li>
 *   <li>{@link com.hypermodel.games.engine.gameDSL.GamePlatformConfig#getIosmoe <em>Iosmoe</em>}</li>
 * </ul>
 *
 * @see com.hypermodel.games.engine.gameDSL.GameDSLPackage#getGamePlatformConfig()
 * @model
 * @generated
 */
public interface GamePlatformConfig extends EObject
{
  /**
   * Returns the value of the '<em><b>Android</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Android</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Android</em>' containment reference.
   * @see #setAndroid(GamePlatformConfigAndroid)
   * @see com.hypermodel.games.engine.gameDSL.GameDSLPackage#getGamePlatformConfig_Android()
   * @model containment="true"
   * @generated
   */
  GamePlatformConfigAndroid getAndroid();

  /**
   * Sets the value of the '{@link com.hypermodel.games.engine.gameDSL.GamePlatformConfig#getAndroid <em>Android</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Android</em>' containment reference.
   * @see #getAndroid()
   * @generated
   */
  void setAndroid(GamePlatformConfigAndroid value);

  /**
   * Returns the value of the '<em><b>Ios</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ios</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ios</em>' containment reference.
   * @see #setIos(GamePlatformConfigIOS)
   * @see com.hypermodel.games.engine.gameDSL.GameDSLPackage#getGamePlatformConfig_Ios()
   * @model containment="true"
   * @generated
   */
  GamePlatformConfigIOS getIos();

  /**
   * Sets the value of the '{@link com.hypermodel.games.engine.gameDSL.GamePlatformConfig#getIos <em>Ios</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ios</em>' containment reference.
   * @see #getIos()
   * @generated
   */
  void setIos(GamePlatformConfigIOS value);

  /**
   * Returns the value of the '<em><b>Iosmoe</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Iosmoe</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Iosmoe</em>' containment reference.
   * @see #setIosmoe(GamePlatformConfigIOSMOE)
   * @see com.hypermodel.games.engine.gameDSL.GameDSLPackage#getGamePlatformConfig_Iosmoe()
   * @model containment="true"
   * @generated
   */
  GamePlatformConfigIOSMOE getIosmoe();

  /**
   * Sets the value of the '{@link com.hypermodel.games.engine.gameDSL.GamePlatformConfig#getIosmoe <em>Iosmoe</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Iosmoe</em>' containment reference.
   * @see #getIosmoe()
   * @generated
   */
  void setIosmoe(GamePlatformConfigIOSMOE value);

} // GamePlatformConfig
