/**
 * generated by hypermodels.com with Xtext 2.13.0
 */
package com.hypermodel.games.engine.gameDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Game Sprite Animation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.hypermodel.games.engine.gameDSL.GameSpriteAnimation#getName <em>Name</em>}</li>
 *   <li>{@link com.hypermodel.games.engine.gameDSL.GameSpriteAnimation#getDuration <em>Duration</em>}</li>
 *   <li>{@link com.hypermodel.games.engine.gameDSL.GameSpriteAnimation#isHasFrames <em>Has Frames</em>}</li>
 *   <li>{@link com.hypermodel.games.engine.gameDSL.GameSpriteAnimation#getFrames <em>Frames</em>}</li>
 *   <li>{@link com.hypermodel.games.engine.gameDSL.GameSpriteAnimation#getOffset <em>Offset</em>}</li>
 *   <li>{@link com.hypermodel.games.engine.gameDSL.GameSpriteAnimation#getRegion <em>Region</em>}</li>
 *   <li>{@link com.hypermodel.games.engine.gameDSL.GameSpriteAnimation#isHasStands <em>Has Stands</em>}</li>
 *   <li>{@link com.hypermodel.games.engine.gameDSL.GameSpriteAnimation#getStands <em>Stands</em>}</li>
 * </ul>
 *
 * @see com.hypermodel.games.engine.gameDSL.GameDSLPackage#getGameSpriteAnimation()
 * @model
 * @generated
 */
public interface GameSpriteAnimation extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.hypermodel.games.engine.gameDSL.GameDSLPackage#getGameSpriteAnimation_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.hypermodel.games.engine.gameDSL.GameSpriteAnimation#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Duration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Duration</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Duration</em>' attribute.
   * @see #setDuration(float)
   * @see com.hypermodel.games.engine.gameDSL.GameDSLPackage#getGameSpriteAnimation_Duration()
   * @model
   * @generated
   */
  float getDuration();

  /**
   * Sets the value of the '{@link com.hypermodel.games.engine.gameDSL.GameSpriteAnimation#getDuration <em>Duration</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Duration</em>' attribute.
   * @see #getDuration()
   * @generated
   */
  void setDuration(float value);

  /**
   * Returns the value of the '<em><b>Has Frames</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Has Frames</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Has Frames</em>' attribute.
   * @see #setHasFrames(boolean)
   * @see com.hypermodel.games.engine.gameDSL.GameDSLPackage#getGameSpriteAnimation_HasFrames()
   * @model
   * @generated
   */
  boolean isHasFrames();

  /**
   * Sets the value of the '{@link com.hypermodel.games.engine.gameDSL.GameSpriteAnimation#isHasFrames <em>Has Frames</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Has Frames</em>' attribute.
   * @see #isHasFrames()
   * @generated
   */
  void setHasFrames(boolean value);

  /**
   * Returns the value of the '<em><b>Frames</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Frames</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Frames</em>' attribute.
   * @see #setFrames(int)
   * @see com.hypermodel.games.engine.gameDSL.GameDSLPackage#getGameSpriteAnimation_Frames()
   * @model
   * @generated
   */
  int getFrames();

  /**
   * Sets the value of the '{@link com.hypermodel.games.engine.gameDSL.GameSpriteAnimation#getFrames <em>Frames</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Frames</em>' attribute.
   * @see #getFrames()
   * @generated
   */
  void setFrames(int value);

  /**
   * Returns the value of the '<em><b>Offset</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Offset</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Offset</em>' attribute.
   * @see #setOffset(int)
   * @see com.hypermodel.games.engine.gameDSL.GameDSLPackage#getGameSpriteAnimation_Offset()
   * @model
   * @generated
   */
  int getOffset();

  /**
   * Sets the value of the '{@link com.hypermodel.games.engine.gameDSL.GameSpriteAnimation#getOffset <em>Offset</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Offset</em>' attribute.
   * @see #getOffset()
   * @generated
   */
  void setOffset(int value);

  /**
   * Returns the value of the '<em><b>Region</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Region</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Region</em>' reference.
   * @see #setRegion(GameTextureRegion)
   * @see com.hypermodel.games.engine.gameDSL.GameDSLPackage#getGameSpriteAnimation_Region()
   * @model
   * @generated
   */
  GameTextureRegion getRegion();

  /**
   * Sets the value of the '{@link com.hypermodel.games.engine.gameDSL.GameSpriteAnimation#getRegion <em>Region</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Region</em>' reference.
   * @see #getRegion()
   * @generated
   */
  void setRegion(GameTextureRegion value);

  /**
   * Returns the value of the '<em><b>Has Stands</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Has Stands</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Has Stands</em>' attribute.
   * @see #setHasStands(boolean)
   * @see com.hypermodel.games.engine.gameDSL.GameDSLPackage#getGameSpriteAnimation_HasStands()
   * @model
   * @generated
   */
  boolean isHasStands();

  /**
   * Sets the value of the '{@link com.hypermodel.games.engine.gameDSL.GameSpriteAnimation#isHasStands <em>Has Stands</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Has Stands</em>' attribute.
   * @see #isHasStands()
   * @generated
   */
  void setHasStands(boolean value);

  /**
   * Returns the value of the '<em><b>Stands</b></em>' containment reference list.
   * The list contents are of type {@link com.hypermodel.games.engine.gameDSL.GameSpriteStand}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Stands</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Stands</em>' containment reference list.
   * @see com.hypermodel.games.engine.gameDSL.GameDSLPackage#getGameSpriteAnimation_Stands()
   * @model containment="true"
   * @generated
   */
  EList<GameSpriteStand> getStands();

} // GameSpriteAnimation
