/**
 * generated by Xtext 2.13.0
 */
package com.hypermodel.games.engine.gameDSL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see com.hypermodel.games.engine.gameDSL.GameDSLFactory
 * @model kind="package"
 * @generated
 */
public interface GameDSLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "gameDSL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.hypermodel.com/games/engine/GameDSL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "gameDSL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  GameDSLPackage eINSTANCE = com.hypermodel.games.engine.gameDSL.impl.GameDSLPackageImpl.init();

  /**
   * The meta object id for the '{@link com.hypermodel.games.engine.gameDSL.impl.GameModelImpl <em>Game Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.hypermodel.games.engine.gameDSL.impl.GameModelImpl
   * @see com.hypermodel.games.engine.gameDSL.impl.GameDSLPackageImpl#getGameModel()
   * @generated
   */
  int GAME_MODEL = 0;

  /**
   * The feature id for the '<em><b>Packages</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_MODEL__PACKAGES = 0;

  /**
   * The number of structural features of the '<em>Game Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.hypermodel.games.engine.gameDSL.impl.GameImportImpl <em>Game Import</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.hypermodel.games.engine.gameDSL.impl.GameImportImpl
   * @see com.hypermodel.games.engine.gameDSL.impl.GameDSLPackageImpl#getGameImport()
   * @generated
   */
  int GAME_IMPORT = 1;

  /**
   * The feature id for the '<em><b>Imported Namespace</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_IMPORT__IMPORTED_NAMESPACE = 0;

  /**
   * The number of structural features of the '<em>Game Import</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_IMPORT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.hypermodel.games.engine.gameDSL.impl.GamePackageImpl <em>Game Package</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.hypermodel.games.engine.gameDSL.impl.GamePackageImpl
   * @see com.hypermodel.games.engine.gameDSL.impl.GameDSLPackageImpl#getGamePackage()
   * @generated
   */
  int GAME_PACKAGE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_PACKAGE__NAME = 0;

  /**
   * The feature id for the '<em><b>Imports</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_PACKAGE__IMPORTS = 1;

  /**
   * The feature id for the '<em><b>Config</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_PACKAGE__CONFIG = 2;

  /**
   * The feature id for the '<em><b>Games</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_PACKAGE__GAMES = 3;

  /**
   * The number of structural features of the '<em>Game Package</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_PACKAGE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link com.hypermodel.games.engine.gameDSL.impl.GamePlatformConfigImpl <em>Game Platform Config</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.hypermodel.games.engine.gameDSL.impl.GamePlatformConfigImpl
   * @see com.hypermodel.games.engine.gameDSL.impl.GameDSLPackageImpl#getGamePlatformConfig()
   * @generated
   */
  int GAME_PLATFORM_CONFIG = 3;

  /**
   * The feature id for the '<em><b>Android</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_PLATFORM_CONFIG__ANDROID = 0;

  /**
   * The feature id for the '<em><b>Ios</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_PLATFORM_CONFIG__IOS = 1;

  /**
   * The number of structural features of the '<em>Game Platform Config</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_PLATFORM_CONFIG_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.hypermodel.games.engine.gameDSL.impl.GamePlatformConfigAndroidImpl <em>Game Platform Config Android</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.hypermodel.games.engine.gameDSL.impl.GamePlatformConfigAndroidImpl
   * @see com.hypermodel.games.engine.gameDSL.impl.GameDSLPackageImpl#getGamePlatformConfigAndroid()
   * @generated
   */
  int GAME_PLATFORM_CONFIG_ANDROID = 4;

  /**
   * The feature id for the '<em><b>Min Android Version</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_PLATFORM_CONFIG_ANDROID__MIN_ANDROID_VERSION = 0;

  /**
   * The feature id for the '<em><b>Target Android Version</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_PLATFORM_CONFIG_ANDROID__TARGET_ANDROID_VERSION = 1;

  /**
   * The feature id for the '<em><b>Api Level</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_PLATFORM_CONFIG_ANDROID__API_LEVEL = 2;

  /**
   * The feature id for the '<em><b>Orientation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_PLATFORM_CONFIG_ANDROID__ORIENTATION = 3;

  /**
   * The feature id for the '<em><b>App Icon</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_PLATFORM_CONFIG_ANDROID__APP_ICON = 4;

  /**
   * The feature id for the '<em><b>App Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_PLATFORM_CONFIG_ANDROID__APP_NAME = 5;

  /**
   * The feature id for the '<em><b>App Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_PLATFORM_CONFIG_ANDROID__APP_LABEL = 6;

  /**
   * The feature id for the '<em><b>Use Accelerometer</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_PLATFORM_CONFIG_ANDROID__USE_ACCELEROMETER = 7;

  /**
   * The number of structural features of the '<em>Game Platform Config Android</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_PLATFORM_CONFIG_ANDROID_FEATURE_COUNT = 8;

  /**
   * The meta object id for the '{@link com.hypermodel.games.engine.gameDSL.impl.GamePlatformConfigIOSImpl <em>Game Platform Config IOS</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.hypermodel.games.engine.gameDSL.impl.GamePlatformConfigIOSImpl
   * @see com.hypermodel.games.engine.gameDSL.impl.GameDSLPackageImpl#getGamePlatformConfigIOS()
   * @generated
   */
  int GAME_PLATFORM_CONFIG_IOS = 5;

  /**
   * The feature id for the '<em><b>Use Accelerometer</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_PLATFORM_CONFIG_IOS__USE_ACCELEROMETER = 0;

  /**
   * The number of structural features of the '<em>Game Platform Config IOS</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_PLATFORM_CONFIG_IOS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.hypermodel.games.engine.gameDSL.impl.GamePlatformConfigurationImpl <em>Game Platform Configuration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.hypermodel.games.engine.gameDSL.impl.GamePlatformConfigurationImpl
   * @see com.hypermodel.games.engine.gameDSL.impl.GameDSLPackageImpl#getGamePlatformConfiguration()
   * @generated
   */
  int GAME_PLATFORM_CONFIGURATION = 6;

  /**
   * The feature id for the '<em><b>Platform</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_PLATFORM_CONFIGURATION__PLATFORM = 0;

  /**
   * The feature id for the '<em><b>Config</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_PLATFORM_CONFIGURATION__CONFIG = 1;

  /**
   * The number of structural features of the '<em>Game Platform Configuration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_PLATFORM_CONFIGURATION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.hypermodel.games.engine.gameDSL.impl.GameImpl <em>Game</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.hypermodel.games.engine.gameDSL.impl.GameImpl
   * @see com.hypermodel.games.engine.gameDSL.impl.GameDSLPackageImpl#getGame()
   * @generated
   */
  int GAME = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME__NAME = 0;

  /**
   * The number of structural features of the '<em>Game</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.hypermodel.games.engine.gameDSL.GamePlatform <em>Game Platform</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.hypermodel.games.engine.gameDSL.GamePlatform
   * @see com.hypermodel.games.engine.gameDSL.impl.GameDSLPackageImpl#getGamePlatform()
   * @generated
   */
  int GAME_PLATFORM = 8;

  /**
   * The meta object id for the '{@link com.hypermodel.games.engine.gameDSL.GameScreenOrientation <em>Game Screen Orientation</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.hypermodel.games.engine.gameDSL.GameScreenOrientation
   * @see com.hypermodel.games.engine.gameDSL.impl.GameDSLPackageImpl#getGameScreenOrientation()
   * @generated
   */
  int GAME_SCREEN_ORIENTATION = 9;


  /**
   * Returns the meta object for class '{@link com.hypermodel.games.engine.gameDSL.GameModel <em>Game Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Game Model</em>'.
   * @see com.hypermodel.games.engine.gameDSL.GameModel
   * @generated
   */
  EClass getGameModel();

  /**
   * Returns the meta object for the containment reference list '{@link com.hypermodel.games.engine.gameDSL.GameModel#getPackages <em>Packages</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Packages</em>'.
   * @see com.hypermodel.games.engine.gameDSL.GameModel#getPackages()
   * @see #getGameModel()
   * @generated
   */
  EReference getGameModel_Packages();

  /**
   * Returns the meta object for class '{@link com.hypermodel.games.engine.gameDSL.GameImport <em>Game Import</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Game Import</em>'.
   * @see com.hypermodel.games.engine.gameDSL.GameImport
   * @generated
   */
  EClass getGameImport();

  /**
   * Returns the meta object for the attribute '{@link com.hypermodel.games.engine.gameDSL.GameImport#getImportedNamespace <em>Imported Namespace</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Imported Namespace</em>'.
   * @see com.hypermodel.games.engine.gameDSL.GameImport#getImportedNamespace()
   * @see #getGameImport()
   * @generated
   */
  EAttribute getGameImport_ImportedNamespace();

  /**
   * Returns the meta object for class '{@link com.hypermodel.games.engine.gameDSL.GamePackage <em>Game Package</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Game Package</em>'.
   * @see com.hypermodel.games.engine.gameDSL.GamePackage
   * @generated
   */
  EClass getGamePackage();

  /**
   * Returns the meta object for the attribute '{@link com.hypermodel.games.engine.gameDSL.GamePackage#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.hypermodel.games.engine.gameDSL.GamePackage#getName()
   * @see #getGamePackage()
   * @generated
   */
  EAttribute getGamePackage_Name();

  /**
   * Returns the meta object for the containment reference list '{@link com.hypermodel.games.engine.gameDSL.GamePackage#getImports <em>Imports</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Imports</em>'.
   * @see com.hypermodel.games.engine.gameDSL.GamePackage#getImports()
   * @see #getGamePackage()
   * @generated
   */
  EReference getGamePackage_Imports();

  /**
   * Returns the meta object for the containment reference '{@link com.hypermodel.games.engine.gameDSL.GamePackage#getConfig <em>Config</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Config</em>'.
   * @see com.hypermodel.games.engine.gameDSL.GamePackage#getConfig()
   * @see #getGamePackage()
   * @generated
   */
  EReference getGamePackage_Config();

  /**
   * Returns the meta object for the containment reference list '{@link com.hypermodel.games.engine.gameDSL.GamePackage#getGames <em>Games</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Games</em>'.
   * @see com.hypermodel.games.engine.gameDSL.GamePackage#getGames()
   * @see #getGamePackage()
   * @generated
   */
  EReference getGamePackage_Games();

  /**
   * Returns the meta object for class '{@link com.hypermodel.games.engine.gameDSL.GamePlatformConfig <em>Game Platform Config</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Game Platform Config</em>'.
   * @see com.hypermodel.games.engine.gameDSL.GamePlatformConfig
   * @generated
   */
  EClass getGamePlatformConfig();

  /**
   * Returns the meta object for the containment reference '{@link com.hypermodel.games.engine.gameDSL.GamePlatformConfig#getAndroid <em>Android</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Android</em>'.
   * @see com.hypermodel.games.engine.gameDSL.GamePlatformConfig#getAndroid()
   * @see #getGamePlatformConfig()
   * @generated
   */
  EReference getGamePlatformConfig_Android();

  /**
   * Returns the meta object for the containment reference '{@link com.hypermodel.games.engine.gameDSL.GamePlatformConfig#getIos <em>Ios</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ios</em>'.
   * @see com.hypermodel.games.engine.gameDSL.GamePlatformConfig#getIos()
   * @see #getGamePlatformConfig()
   * @generated
   */
  EReference getGamePlatformConfig_Ios();

  /**
   * Returns the meta object for class '{@link com.hypermodel.games.engine.gameDSL.GamePlatformConfigAndroid <em>Game Platform Config Android</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Game Platform Config Android</em>'.
   * @see com.hypermodel.games.engine.gameDSL.GamePlatformConfigAndroid
   * @generated
   */
  EClass getGamePlatformConfigAndroid();

  /**
   * Returns the meta object for the attribute '{@link com.hypermodel.games.engine.gameDSL.GamePlatformConfigAndroid#getMinAndroidVersion <em>Min Android Version</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Min Android Version</em>'.
   * @see com.hypermodel.games.engine.gameDSL.GamePlatformConfigAndroid#getMinAndroidVersion()
   * @see #getGamePlatformConfigAndroid()
   * @generated
   */
  EAttribute getGamePlatformConfigAndroid_MinAndroidVersion();

  /**
   * Returns the meta object for the attribute '{@link com.hypermodel.games.engine.gameDSL.GamePlatformConfigAndroid#getTargetAndroidVersion <em>Target Android Version</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Target Android Version</em>'.
   * @see com.hypermodel.games.engine.gameDSL.GamePlatformConfigAndroid#getTargetAndroidVersion()
   * @see #getGamePlatformConfigAndroid()
   * @generated
   */
  EAttribute getGamePlatformConfigAndroid_TargetAndroidVersion();

  /**
   * Returns the meta object for the attribute '{@link com.hypermodel.games.engine.gameDSL.GamePlatformConfigAndroid#getApiLevel <em>Api Level</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Api Level</em>'.
   * @see com.hypermodel.games.engine.gameDSL.GamePlatformConfigAndroid#getApiLevel()
   * @see #getGamePlatformConfigAndroid()
   * @generated
   */
  EAttribute getGamePlatformConfigAndroid_ApiLevel();

  /**
   * Returns the meta object for the attribute '{@link com.hypermodel.games.engine.gameDSL.GamePlatformConfigAndroid#getOrientation <em>Orientation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Orientation</em>'.
   * @see com.hypermodel.games.engine.gameDSL.GamePlatformConfigAndroid#getOrientation()
   * @see #getGamePlatformConfigAndroid()
   * @generated
   */
  EAttribute getGamePlatformConfigAndroid_Orientation();

  /**
   * Returns the meta object for the attribute '{@link com.hypermodel.games.engine.gameDSL.GamePlatformConfigAndroid#getAppIcon <em>App Icon</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>App Icon</em>'.
   * @see com.hypermodel.games.engine.gameDSL.GamePlatformConfigAndroid#getAppIcon()
   * @see #getGamePlatformConfigAndroid()
   * @generated
   */
  EAttribute getGamePlatformConfigAndroid_AppIcon();

  /**
   * Returns the meta object for the attribute '{@link com.hypermodel.games.engine.gameDSL.GamePlatformConfigAndroid#getAppName <em>App Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>App Name</em>'.
   * @see com.hypermodel.games.engine.gameDSL.GamePlatformConfigAndroid#getAppName()
   * @see #getGamePlatformConfigAndroid()
   * @generated
   */
  EAttribute getGamePlatformConfigAndroid_AppName();

  /**
   * Returns the meta object for the attribute '{@link com.hypermodel.games.engine.gameDSL.GamePlatformConfigAndroid#getAppLabel <em>App Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>App Label</em>'.
   * @see com.hypermodel.games.engine.gameDSL.GamePlatformConfigAndroid#getAppLabel()
   * @see #getGamePlatformConfigAndroid()
   * @generated
   */
  EAttribute getGamePlatformConfigAndroid_AppLabel();

  /**
   * Returns the meta object for the attribute '{@link com.hypermodel.games.engine.gameDSL.GamePlatformConfigAndroid#isUseAccelerometer <em>Use Accelerometer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Use Accelerometer</em>'.
   * @see com.hypermodel.games.engine.gameDSL.GamePlatformConfigAndroid#isUseAccelerometer()
   * @see #getGamePlatformConfigAndroid()
   * @generated
   */
  EAttribute getGamePlatformConfigAndroid_UseAccelerometer();

  /**
   * Returns the meta object for class '{@link com.hypermodel.games.engine.gameDSL.GamePlatformConfigIOS <em>Game Platform Config IOS</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Game Platform Config IOS</em>'.
   * @see com.hypermodel.games.engine.gameDSL.GamePlatformConfigIOS
   * @generated
   */
  EClass getGamePlatformConfigIOS();

  /**
   * Returns the meta object for the attribute '{@link com.hypermodel.games.engine.gameDSL.GamePlatformConfigIOS#isUseAccelerometer <em>Use Accelerometer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Use Accelerometer</em>'.
   * @see com.hypermodel.games.engine.gameDSL.GamePlatformConfigIOS#isUseAccelerometer()
   * @see #getGamePlatformConfigIOS()
   * @generated
   */
  EAttribute getGamePlatformConfigIOS_UseAccelerometer();

  /**
   * Returns the meta object for class '{@link com.hypermodel.games.engine.gameDSL.GamePlatformConfiguration <em>Game Platform Configuration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Game Platform Configuration</em>'.
   * @see com.hypermodel.games.engine.gameDSL.GamePlatformConfiguration
   * @generated
   */
  EClass getGamePlatformConfiguration();

  /**
   * Returns the meta object for the attribute '{@link com.hypermodel.games.engine.gameDSL.GamePlatformConfiguration#getPlatform <em>Platform</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Platform</em>'.
   * @see com.hypermodel.games.engine.gameDSL.GamePlatformConfiguration#getPlatform()
   * @see #getGamePlatformConfiguration()
   * @generated
   */
  EAttribute getGamePlatformConfiguration_Platform();

  /**
   * Returns the meta object for the containment reference list '{@link com.hypermodel.games.engine.gameDSL.GamePlatformConfiguration#getConfig <em>Config</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Config</em>'.
   * @see com.hypermodel.games.engine.gameDSL.GamePlatformConfiguration#getConfig()
   * @see #getGamePlatformConfiguration()
   * @generated
   */
  EReference getGamePlatformConfiguration_Config();

  /**
   * Returns the meta object for class '{@link com.hypermodel.games.engine.gameDSL.Game <em>Game</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Game</em>'.
   * @see com.hypermodel.games.engine.gameDSL.Game
   * @generated
   */
  EClass getGame();

  /**
   * Returns the meta object for the attribute '{@link com.hypermodel.games.engine.gameDSL.Game#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.hypermodel.games.engine.gameDSL.Game#getName()
   * @see #getGame()
   * @generated
   */
  EAttribute getGame_Name();

  /**
   * Returns the meta object for enum '{@link com.hypermodel.games.engine.gameDSL.GamePlatform <em>Game Platform</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Game Platform</em>'.
   * @see com.hypermodel.games.engine.gameDSL.GamePlatform
   * @generated
   */
  EEnum getGamePlatform();

  /**
   * Returns the meta object for enum '{@link com.hypermodel.games.engine.gameDSL.GameScreenOrientation <em>Game Screen Orientation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Game Screen Orientation</em>'.
   * @see com.hypermodel.games.engine.gameDSL.GameScreenOrientation
   * @generated
   */
  EEnum getGameScreenOrientation();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  GameDSLFactory getGameDSLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link com.hypermodel.games.engine.gameDSL.impl.GameModelImpl <em>Game Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.hypermodel.games.engine.gameDSL.impl.GameModelImpl
     * @see com.hypermodel.games.engine.gameDSL.impl.GameDSLPackageImpl#getGameModel()
     * @generated
     */
    EClass GAME_MODEL = eINSTANCE.getGameModel();

    /**
     * The meta object literal for the '<em><b>Packages</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAME_MODEL__PACKAGES = eINSTANCE.getGameModel_Packages();

    /**
     * The meta object literal for the '{@link com.hypermodel.games.engine.gameDSL.impl.GameImportImpl <em>Game Import</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.hypermodel.games.engine.gameDSL.impl.GameImportImpl
     * @see com.hypermodel.games.engine.gameDSL.impl.GameDSLPackageImpl#getGameImport()
     * @generated
     */
    EClass GAME_IMPORT = eINSTANCE.getGameImport();

    /**
     * The meta object literal for the '<em><b>Imported Namespace</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GAME_IMPORT__IMPORTED_NAMESPACE = eINSTANCE.getGameImport_ImportedNamespace();

    /**
     * The meta object literal for the '{@link com.hypermodel.games.engine.gameDSL.impl.GamePackageImpl <em>Game Package</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.hypermodel.games.engine.gameDSL.impl.GamePackageImpl
     * @see com.hypermodel.games.engine.gameDSL.impl.GameDSLPackageImpl#getGamePackage()
     * @generated
     */
    EClass GAME_PACKAGE = eINSTANCE.getGamePackage();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GAME_PACKAGE__NAME = eINSTANCE.getGamePackage_Name();

    /**
     * The meta object literal for the '<em><b>Imports</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAME_PACKAGE__IMPORTS = eINSTANCE.getGamePackage_Imports();

    /**
     * The meta object literal for the '<em><b>Config</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAME_PACKAGE__CONFIG = eINSTANCE.getGamePackage_Config();

    /**
     * The meta object literal for the '<em><b>Games</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAME_PACKAGE__GAMES = eINSTANCE.getGamePackage_Games();

    /**
     * The meta object literal for the '{@link com.hypermodel.games.engine.gameDSL.impl.GamePlatformConfigImpl <em>Game Platform Config</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.hypermodel.games.engine.gameDSL.impl.GamePlatformConfigImpl
     * @see com.hypermodel.games.engine.gameDSL.impl.GameDSLPackageImpl#getGamePlatformConfig()
     * @generated
     */
    EClass GAME_PLATFORM_CONFIG = eINSTANCE.getGamePlatformConfig();

    /**
     * The meta object literal for the '<em><b>Android</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAME_PLATFORM_CONFIG__ANDROID = eINSTANCE.getGamePlatformConfig_Android();

    /**
     * The meta object literal for the '<em><b>Ios</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAME_PLATFORM_CONFIG__IOS = eINSTANCE.getGamePlatformConfig_Ios();

    /**
     * The meta object literal for the '{@link com.hypermodel.games.engine.gameDSL.impl.GamePlatformConfigAndroidImpl <em>Game Platform Config Android</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.hypermodel.games.engine.gameDSL.impl.GamePlatformConfigAndroidImpl
     * @see com.hypermodel.games.engine.gameDSL.impl.GameDSLPackageImpl#getGamePlatformConfigAndroid()
     * @generated
     */
    EClass GAME_PLATFORM_CONFIG_ANDROID = eINSTANCE.getGamePlatformConfigAndroid();

    /**
     * The meta object literal for the '<em><b>Min Android Version</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GAME_PLATFORM_CONFIG_ANDROID__MIN_ANDROID_VERSION = eINSTANCE.getGamePlatformConfigAndroid_MinAndroidVersion();

    /**
     * The meta object literal for the '<em><b>Target Android Version</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GAME_PLATFORM_CONFIG_ANDROID__TARGET_ANDROID_VERSION = eINSTANCE.getGamePlatformConfigAndroid_TargetAndroidVersion();

    /**
     * The meta object literal for the '<em><b>Api Level</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GAME_PLATFORM_CONFIG_ANDROID__API_LEVEL = eINSTANCE.getGamePlatformConfigAndroid_ApiLevel();

    /**
     * The meta object literal for the '<em><b>Orientation</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GAME_PLATFORM_CONFIG_ANDROID__ORIENTATION = eINSTANCE.getGamePlatformConfigAndroid_Orientation();

    /**
     * The meta object literal for the '<em><b>App Icon</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GAME_PLATFORM_CONFIG_ANDROID__APP_ICON = eINSTANCE.getGamePlatformConfigAndroid_AppIcon();

    /**
     * The meta object literal for the '<em><b>App Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GAME_PLATFORM_CONFIG_ANDROID__APP_NAME = eINSTANCE.getGamePlatformConfigAndroid_AppName();

    /**
     * The meta object literal for the '<em><b>App Label</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GAME_PLATFORM_CONFIG_ANDROID__APP_LABEL = eINSTANCE.getGamePlatformConfigAndroid_AppLabel();

    /**
     * The meta object literal for the '<em><b>Use Accelerometer</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GAME_PLATFORM_CONFIG_ANDROID__USE_ACCELEROMETER = eINSTANCE.getGamePlatformConfigAndroid_UseAccelerometer();

    /**
     * The meta object literal for the '{@link com.hypermodel.games.engine.gameDSL.impl.GamePlatformConfigIOSImpl <em>Game Platform Config IOS</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.hypermodel.games.engine.gameDSL.impl.GamePlatformConfigIOSImpl
     * @see com.hypermodel.games.engine.gameDSL.impl.GameDSLPackageImpl#getGamePlatformConfigIOS()
     * @generated
     */
    EClass GAME_PLATFORM_CONFIG_IOS = eINSTANCE.getGamePlatformConfigIOS();

    /**
     * The meta object literal for the '<em><b>Use Accelerometer</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GAME_PLATFORM_CONFIG_IOS__USE_ACCELEROMETER = eINSTANCE.getGamePlatformConfigIOS_UseAccelerometer();

    /**
     * The meta object literal for the '{@link com.hypermodel.games.engine.gameDSL.impl.GamePlatformConfigurationImpl <em>Game Platform Configuration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.hypermodel.games.engine.gameDSL.impl.GamePlatformConfigurationImpl
     * @see com.hypermodel.games.engine.gameDSL.impl.GameDSLPackageImpl#getGamePlatformConfiguration()
     * @generated
     */
    EClass GAME_PLATFORM_CONFIGURATION = eINSTANCE.getGamePlatformConfiguration();

    /**
     * The meta object literal for the '<em><b>Platform</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GAME_PLATFORM_CONFIGURATION__PLATFORM = eINSTANCE.getGamePlatformConfiguration_Platform();

    /**
     * The meta object literal for the '<em><b>Config</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAME_PLATFORM_CONFIGURATION__CONFIG = eINSTANCE.getGamePlatformConfiguration_Config();

    /**
     * The meta object literal for the '{@link com.hypermodel.games.engine.gameDSL.impl.GameImpl <em>Game</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.hypermodel.games.engine.gameDSL.impl.GameImpl
     * @see com.hypermodel.games.engine.gameDSL.impl.GameDSLPackageImpl#getGame()
     * @generated
     */
    EClass GAME = eINSTANCE.getGame();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GAME__NAME = eINSTANCE.getGame_Name();

    /**
     * The meta object literal for the '{@link com.hypermodel.games.engine.gameDSL.GamePlatform <em>Game Platform</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.hypermodel.games.engine.gameDSL.GamePlatform
     * @see com.hypermodel.games.engine.gameDSL.impl.GameDSLPackageImpl#getGamePlatform()
     * @generated
     */
    EEnum GAME_PLATFORM = eINSTANCE.getGamePlatform();

    /**
     * The meta object literal for the '{@link com.hypermodel.games.engine.gameDSL.GameScreenOrientation <em>Game Screen Orientation</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.hypermodel.games.engine.gameDSL.GameScreenOrientation
     * @see com.hypermodel.games.engine.gameDSL.impl.GameDSLPackageImpl#getGameScreenOrientation()
     * @generated
     */
    EEnum GAME_SCREEN_ORIENTATION = eINSTANCE.getGameScreenOrientation();

  }

} //GameDSLPackage
