/**
 * generated by hypermodels.com with Xtext 2.13.0
 */
package com.hypermodel.games.engine.gameDSL;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see com.hypermodel.games.engine.gameDSL.GameDSLPackage
 * @generated
 */
public interface GameDSLFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  GameDSLFactory eINSTANCE = com.hypermodel.games.engine.gameDSL.impl.GameDSLFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Game Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Game Model</em>'.
   * @generated
   */
  GameModel createGameModel();

  /**
   * Returns a new object of class '<em>Game Package</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Game Package</em>'.
   * @generated
   */
  GamePackage createGamePackage();

  /**
   * Returns a new object of class '<em>Game Platform Config</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Game Platform Config</em>'.
   * @generated
   */
  GamePlatformConfig createGamePlatformConfig();

  /**
   * Returns a new object of class '<em>Game Platform Config Android</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Game Platform Config Android</em>'.
   * @generated
   */
  GamePlatformConfigAndroid createGamePlatformConfigAndroid();

  /**
   * Returns a new object of class '<em>Game Platform Config IOS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Game Platform Config IOS</em>'.
   * @generated
   */
  GamePlatformConfigIOS createGamePlatformConfigIOS();

  /**
   * Returns a new object of class '<em>Game Platform Config IOSMOE</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Game Platform Config IOSMOE</em>'.
   * @generated
   */
  GamePlatformConfigIOSMOE createGamePlatformConfigIOSMOE();

  /**
   * Returns a new object of class '<em>Game Root</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Game Root</em>'.
   * @generated
   */
  GameRoot createGameRoot();

  /**
   * Returns a new object of class '<em>Game Screen</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Game Screen</em>'.
   * @generated
   */
  GameScreen createGameScreen();

  /**
   * Returns a new object of class '<em>Game Scene</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Game Scene</em>'.
   * @generated
   */
  GameScene createGameScene();

  /**
   * Returns a new object of class '<em>Game Score</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Game Score</em>'.
   * @generated
   */
  GameScore createGameScore();

  /**
   * Returns a new object of class '<em>Game Display</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Game Display</em>'.
   * @generated
   */
  GameDisplay createGameDisplay();

  /**
   * Returns a new object of class '<em>Game Tile</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Game Tile</em>'.
   * @generated
   */
  GameTile createGameTile();

  /**
   * Returns a new object of class '<em>Game Sprite</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Game Sprite</em>'.
   * @generated
   */
  GameSprite createGameSprite();

  /**
   * Returns a new object of class '<em>Game Vector2d</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Game Vector2d</em>'.
   * @generated
   */
  GameVector2d createGameVector2d();

  /**
   * Returns a new object of class '<em>Game Sprite State</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Game Sprite State</em>'.
   * @generated
   */
  GameSpriteState createGameSpriteState();

  /**
   * Returns a new object of class '<em>Game Body Property</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Game Body Property</em>'.
   * @generated
   */
  GameBodyProperty createGameBodyProperty();

  /**
   * Returns a new object of class '<em>Game Rule</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Game Rule</em>'.
   * @generated
   */
  GameRule createGameRule();

  /**
   * Returns a new object of class '<em>Game Sprite Animation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Game Sprite Animation</em>'.
   * @generated
   */
  GameSpriteAnimation createGameSpriteAnimation();

  /**
   * Returns a new object of class '<em>Game Sprite Stand</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Game Sprite Stand</em>'.
   * @generated
   */
  GameSpriteStand createGameSpriteStand();

  /**
   * Returns a new object of class '<em>Game Texture Region</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Game Texture Region</em>'.
   * @generated
   */
  GameTextureRegion createGameTextureRegion();

  /**
   * Returns a new object of class '<em>Game Sprite Event</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Game Sprite Event</em>'.
   * @generated
   */
  GameSpriteEvent createGameSpriteEvent();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  GameDSLPackage getGameDSLPackage();

} //GameDSLFactory
